language: python
python:
- '3.4'
- '3.5'
- '3.6'
matrix:
  fast_finish: true
before_install:
- sudo apt-get -qq update
install:
- pip install -U pip
- pip install -U setuptools
- pip install tox-travis codecov
script:
- tox
after_success:
- codecov
before_deploy:
- sudo apt-get -qq install pandoc
- pip install pypandoc
deploy:
  provider: pypi
  user: benmaddison
  distributions: sdist bdist_wheel
  password:
    secure: o4qUYXQ8AdljQg1NVxD3o4H6yBkyG+jlgwwxDAu9CN3yZq0sgz7rMFhZFmKFXWimgOeaByabN9ASf0lPX73zmoz++6g0fh9oh1nwkww1vmOo8glpNQxxq8KqX8XLi2u89DQwF0usWEvdwLDnClJBegbMaRLcs9Dt+/++NgAFkm3uGzwhRFsWKDp2Rz6YCUNEeJh3rEq3HT/YEHXVZCF9siWu76xc5duaqDrUNrrUD/J+ktp1zaqrutVbtJlQiWHW4Vnm2HlUSKrrVm6M1lgbUh5gSLKxfq7/uvjD/SHFZRgwrLFlzImT3C/OliWM6V4ByCbegrxTIgmJRVXKKf2A1pTRnUACO/4qRCjCrbT6T9jI2KAHvykEvRyvERnl3J2OO6pIXPrX5Pjlw3AqWaZtm04RykiWq2dH32qYxKMnx2tl/qniPktmyy9OqxKMEloKMxEYqy8Rn/r0WXK8aFLNShF4xJpBo07J2BlX1fAmqt2mi6J90S+V+97qN77A2jg72HkG+3sLcBXUTtblnI4qVRQTf+LUIX0QLQXL5zgw2Kjk5cypzVz9Sc2vYREkacQj03cega8bCezKAQ6jOtnKKlQ21mrqua9s+n4++foSkmAWf6j/cTr/mXyBJOkVUQLUQdDRp1A5Ugxre0Yg3FKGYuYuraec2qAlw39G2kP525w=
  on:
    tags: true
    python: '3.6'
