language: python
python:
- '3.4'
- '3.5'
- '3.6'
matrix:
  fast_finish: true
before_install:
- sudo apt-get -qq update
install:
- pip install -U pip
- pip install -U setuptools
- pip install tox-travis codecov
script:
- tox
after_success:
- codecov
before_deploy:
- sudo apt-get -qq install pandoc
- pip install pypandoc
deploy:
  provider: pypi
  user: benmaddison
  distributions: sdist bdist_wheel
  password:
    secure: Kc+5Bld3IyM4S01dR0dQxQYUFeiwrYB81HsUPmIwqlS40pTRsF5U0iW2qzFvXz+DWXqJQ33BnQZAKxiQ/+V2l9Id4AdvuUQvgqAJ0ywfsGIBV31pIZ7/2w1HtO0JkAAxW5zSjzvqGL5kofeJb6hBEdsxYwKUinKsHvDA/3QgTriOZQ6W52bMbQBGNMlnehCS/Q3/zsWMhhoNBxFM9PWTNeoARwj0Oza7rOZYLZP9q4YqKeTzIu58Ks2gvPPZr5v/v146NfVwnUjDWnQflGll+nibYc4sNcOPDvNrMN+YPl51QpIsGRXUumzNgHsyQxwsLybK3/kD/ZTs58HTQf849H1+gVG3ETeYkubcwIRmy3SF0w7WlNxGSbdfwZlvY5OBQ9Q5Azdpj5MJ+TJNe40mOSlkO5DUqgm+ugh4VTPHEyxRAUCLhnb4eRx55hd5RffsYeB8G2zuFBlRrvODx4OMf4WYL50uy8ICJk23WYPBX3QC0JKauoACqMUtOUDii2g44jH8jhYV3PeD9g3vBStNeA7ELEdoL1JWZOsAPHXWepI1mFg+ouZlyozofXesqHHjQzbgo8auMPnKYdm0tNKARGG9l8e0VOs/bBzva/DtyjWBG6jk0dDVRxAzLhRHBYMd1J6U1c6KbayPlqXMfxLsRJqUUy6fdNTXb/IL/DsS0Js=
  on:
    tags: true
    python: '3.6'
